(docs) Update `about.md`
AsahiLinux/AsahiLinux.github.io pull request #4
Opened 2021-01-05 23:02 UTC by vladdoster

- Spelling
- Grammar

2021-01-06 13:04 UTC, marcan requested changes

2021-01-06 13:04 UTC, marcan commented on content/about.md
> +All development takes place on our [GitHub](https://github.com/AsahiLinux). All contributions will be written to upstream them into the respective upstream projects (starting with the Linux kernel) a
The point of "with the intent" was to say that the code will be written with the idea of upstreaming it (i.e. written to be clean enough / architected to be upstreamable). "as early as is practical" is also not quite the same as "as early as possible"; I'm not going to literally optimize for fastest-upstream, because that actually adds overhead (more changes end up going upstream if the code is in flux). Hence, "as early as is practical" is intended to mean that I will send fairly-complete snapshots upstream when they reach useful milestones; not firing off merge requests all the time, but also not sitting on good code for extended periods of time.

2021-01-06 13:04 UTC, marcan commented on content/about.md
> +No, Apple still controls the boot process and, for example, the firmware that runs on the Secure Enclave Processor. However, no modern device is "fully open" - no usable computer exists today with co
"at any time" is correct English; "anytime" in your version is correct too, but more casual. I prefer the original version.

Similarly, I think the ", as the" version is fine? Can you explain the reason for this change?

2021-01-06 13:04 UTC, marcan commented on content/about.md
> +Asahi Linux is a community, and we invite anyone to contribute. Marcan currently leads the project, but many other contributors also participate. If you are interested in contributing, check out our
Actually, this should probably be "everyone is invited", not "anyone is invited" :)

My handle is always written with a lowercase 'm'; this is a stylistic choice that is intended to override typical grammatical rules.

2021-01-06 13:04 UTC, marcan commented on content/about.md
> +## Who is this Marcan guy?
Same story about the lowercase 'm'.

2021-01-06 13:04 UTC, marcan commented on content/about.md
> +* [PS4 Linux](https://github.com/fail0verflow/ps4-linux), a Linux port to the proprietary hardware found on the PS4, capable of full 3D acceleration using OpenGL and Vulkan (Radeon/AMD GPU drivers).
These are literal module/driver names and are correct in the original version.

2021-01-07 12:22 UTC, vladdoster commented on content/about.md
> +All development takes place on our [GitHub](https://github.com/AsahiLinux). All contributions will be written to upstream them into the respective upstream projects (starting with the Linux kernel) a
@marcan Hi, thank you for the insightful feedback regarding the changes. Reverted.

2021-01-07 12:57 UTC, vladdoster commented on content/about.md
> +No, Apple still controls the boot process and, for example, the firmware that runs on the Secure Enclave Processor. However, no modern device is "fully open" - no usable computer exists today with co
1. Agreed, great call out.

2. The two sentences in your question are both grammatically correct and both idiomatic native-speaker versions of the same semantic content. However, `as` is often ambiguous, but `because` never is. `because` is your best choice for clear, correct, unambiguous communication, especially if you want to be understood easily by other non-native speakers.

2021-01-07 13:03 UTC, vladdoster commented on content/about.md
> +* [PS4 Linux](https://github.com/fail0verflow/ps4-linux), a Linux port to the proprietary hardware found on the PS4, capable of full 3D acceleration using OpenGL and Vulkan (Radeon/AMD GPU drivers).
Ah okay. I checked the [relevant arch wiki page](https://wiki.archlinux.org/index.php/AMDGPU) and changed it accordingly.

2021-01-07 18:43 UTC, marcan commented on content/about.md
> +No, Apple still controls the boot process and, for example, the firmware that runs on the Secure Enclave Processor. However, no modern device is "fully open" - no usable computer exists today with co
Good point on "because" and non-native speakers. Perhaps "because the"? Somehow without the "the" it reads to me like "proprietary firmware (only)", while it's more like I'm making the assumption the firmware is proprietary (as it almost always is on these platforms) and just describing what the firmware does.

2021-01-08 12:06 UTC, vladdoster commented on content/about.md
> +No, Apple still controls the boot process and, for example, the firmware that runs on the Secure Enclave Processor. However, no modern device is "fully open" - no usable computer exists today with co
Added `the`. Resolved

2021-01-08 12:13 UTC, marcan approved these changes

2021-01-08 12:13 UTC, merged